- id: pyproject-version-sync
  name: pyproject-version-sync
  description: Checks that the project version in pyproject.toml is aligned with the repository tag
  entry: sync_pyproject_version
  language: python
  files: ^pyproject\.toml$
