- id: pyproject-version-check
  name: pyproject-version-check
  description: Checks that the project version in pyproject.toml is aligned with the repository tag
  entry: align_pyproject_version
  language: python
  files: ^pyproject\.toml$
